'use client';

import { useEffect, useRef } from 'react';
import ResultCard from './ResultCard';
import type { Session, QuickPrompt } from '@/types';

interface ChatPanelProps {
  session: Session;
  quickPrompts: QuickPrompt[];
  onQuickPrompt: (text: string) => void;
}

export default function ChatPanel({ session, quickPrompts, onQuickPrompt }: ChatPanelProps) {
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [session.messages]);

  const isEmpty = session.messages.length === 0;

  return (
    <div className="messages-area">
      {isEmpty ? (
        <WelcomeScreen prompts={quickPrompts} onSelect={onQuickPrompt} />
      ) : (
        <>
          {session.messages.map(msg => {
            if (msg.role === 'thinking') {
              return (
                <div key={msg.id} className="thinking">
                  <div className="msg-inner">
                    <div className="avatar">🔍</div>
                    <div className="dots">
                      <span /><span /><span />
                    </div>
                  </div>
                </div>
              );
            }
            if (msg.role === 'user') {
              return (
                <div key={msg.id} className="msg-row msg-user">
                  <div className="msg-inner">
                    <div className="bubble">{msg.text}</div>
                  </div>
                </div>
              );
            }
            if (msg.role === 'result' && msg.result) {
              return (
                <div key={msg.id} className="msg-row msg-assistant">
                  <div className="msg-inner">
                    <div className="avatar">🔍</div>
                    <div className="assistant-content">
                      <ResultCard result={msg.result} />
                    </div>
                  </div>
                </div>
              );
            }
            if (msg.role === 'error') {
              return (
                <div key={msg.id} className="msg-row msg-assistant">
                  <div className="msg-inner">
                    <div className="avatar" style={{ background: 'var(--ai-color)' }}>!</div>
                    <div className="assistant-content">
                      <div className="error-msg">{msg.text}</div>
                    </div>
                  </div>
                </div>
              );
            }
            return null;
          })}
          <div ref={bottomRef} />
        </>
      )}
    </div>
  );
}

function WelcomeScreen({ prompts, onSelect }: { prompts: QuickPrompt[]; onSelect: (t: string) => void }) {
  return (
    <div className="welcome-wrap">
      <span className="welcome-icon">🔍</span>
      <h1 className="welcome-title">detex<span style={{color:'var(--accent)'}}>.ai</span></h1>
      <p className="welcome-sub">
        Paste any text below to instantly find out whether it was written by a human or generated by AI.
      </p>
      <div className="quick-grid">
        {prompts.map((p, i) => (
          <button
            key={i}
            id={`quick-${i}`}
            className="quick-card"
            onClick={() => onSelect(p.text)}
          >
            <div className="quick-card-title">{p.title}</div>
            <div className="quick-card-sub">{p.sub}</div>
          </button>
        ))}
      </div>
    </div>
  );
}
