import Link from 'next/link';
import LogoMark from '@/components/LogoMark';

export const metadata = {
  title: 'Terms of Service — detex.ai',
  description: 'Terms and conditions for using detex.ai.',
};

export default function TermsPage() {
  return (
    <div className="legal-shell">
      {/* Nav */}
      <nav className="legal-nav">
        <Link href="/" className="legal-logo">
          <LogoMark size={26} />
          <span>detex<span style={{ color: 'var(--accent)' }}>.ai</span></span>
        </Link>
        <Link href="/" className="legal-back">← Back to home</Link>
      </nav>

      <main className="legal-main">
        <div className="legal-header">
          <p className="legal-label">Legal</p>
          <h1>Terms of Service</h1>
          <p className="legal-meta">Last updated: February 2026</p>
        </div>

        <div className="legal-body">
          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using detex.ai (&quot;the Service&quot;), you agree to be bound by these Terms of Service.
              If you do not agree to these terms, please do not use the Service.
              detex.ai is operated by <strong>neurobrain-ai</strong>.
            </p>
          </section>

          <section>
            <h2>2. Description of Service</h2>
            <p>
              detex.ai is an AI-powered text analysis tool that uses machine learning to estimate the likelihood
              that a given piece of text was generated by an AI model or written by a human. The Service is
              provided for informational and research purposes.
            </p>
          </section>

          <section>
            <h2>3. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul>
              <li>Submit content that is illegal, harmful, threatening, or abusive</li>
              <li>Attempt to reverse-engineer, scrape, or overload the API</li>
              <li>Use the Service as the sole basis for consequential decisions affecting individuals (e.g. academic penalties) without human review</li>
              <li>Represent detection results as legally binding determinations</li>
              <li>Circumvent any rate limits or access controls</li>
            </ul>
          </section>

          <section>
            <h2>4. Accuracy Disclaimer</h2>
            <p>
              <strong>AI detection is probabilistic, not deterministic.</strong> Our tool provides confidence scores
              based on statistical models and should be used as a supplementary signal, not a definitive proof of
              AI authorship. We make no warranty that results are accurate, complete, or suitable for any specific
              purpose. False positives and false negatives can and do occur.
            </p>
            <p>
              You are solely responsible for any decisions or actions you take based on the output of our tool.
            </p>
          </section>

          <section>
            <h2>5. Account Responsibility</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials.
              You agree to notify us immediately of any unauthorized use of your account.
              We are not liable for any losses arising from unauthorized access to your account.
            </p>
          </section>

          <section>
            <h2>6. Intellectual Property</h2>
            <p>
              The Service, including its design, code, branding, and machine learning models, is owned by
              neurobrain-ai and protected by applicable intellectual property laws. You may not reproduce,
              distribute, or create derivative works without our written permission.
            </p>
          </section>

          <section>
            <h2>7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, neurobrain-ai shall not be liable for any indirect,
              incidental, special, or consequential damages resulting from your use of the Service,
              including but not limited to loss of data, loss of reputation, or economic loss.
            </p>
          </section>

          <section>
            <h2>8. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at any time, with or
              without notice, if we believe you have violated these Terms or are using the Service in a way
              that harms others.
            </p>
          </section>

          <section>
            <h2>9. Changes to Terms</h2>
            <p>
              We may revise these Terms at any time. We will update the &quot;Last updated&quot; date when we do.
              Continued use of the Service after changes constitutes your acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2>10. Contact</h2>
            <p>
              For questions about these Terms, contact us at{' '}
              <a href="https://sunnakh.com/contact/" target="_blank" rel="noopener noreferrer">sunnakh.com/contact</a>.
            </p>
          </section>
        </div>

        <div className="legal-footer-links">
          <Link href="/privacy">Privacy Policy →</Link>
        </div>
      </main>
    </div>
  );
}
